### ISSUE TITLE
Would be good to ask users for a custom short name, instead of a random hash link

### ISSUE THREAD

**Issue by pratyush1712** [epicdragon44/hyperdti-cu#1]
https://github.com/epicdragon44/hyperdti-cu/blob/5c437800759919a3c55e3a9713f645c073466006/src/services/firebase/firebase.ts#L60

**Comment by danielwei15** [comment]
Oh fs. Let me assign myself this and jump on it after my exams.

**Comment by danielwei15** [comment]
Addressed!
